### ISSUE TITLE
USER STORY: About Page

### ISSUE THREAD

**Issue by kpsdev1** [kpsdev1/The-Recipe-Blog#13]
As a **User** I can **click on the about page** so that **so that i can find out what the website is about and how to use it**

# Acceptance  Criteria 
- Acceptance  Criteria 1: Create an about page that is easily accessible in the top Navigation.
- Acceptance  Criteria 2: Provide information about the site and the aim of the site.
- Acceptance  Criteria 3: Tell the user how to use the site.

# Tasks
- [ ] Create a HTML about page and add a Nav link to the navigation bar.
- [x] Explain clearly what the site is about.
- [x] Explain how to use the site.

**Comment by kpsdev1** [comment]
Instead of being a page itself this will now be a section on the home page.

**Comment by kpsdev1** [comment]
Instead of creating a separate page, the about page is now just a section on the homepage
