### ISSUE TITLE
USER STORY: Add a wine

### ISSUE THREAD

**Issue by kpsdev1** [kpsdev1/The-Recipe-Blog#17]
As a **role** I can **add a wine** that i like so that **other people can see it**

# Acceptance  Criteria 
- When logged in, The user can navigate to the wines page and click on a button to add a wine.
- Once added the wine will display in the wines list.

# Tasks
- [x] Check to make sure the user is logged in.
- [x] Create a button on the Wines page that allows a user to add a wine
- [x] Display the newly added wine in the wines list
