### ISSUE TITLE
USER STORY: View a wine

### ISSUE THREAD

**Issue by kpsdev1** [kpsdev1/The-Recipe-Blog#18]
As a **User** I can **view all wines** so that **I can choose one to see the details**

# Acceptance  Criteria 
- When the user is logged in display all the wines in a list.
- Have a view button on each wine so that the user can view the details of the wine.

# Tasks

- [x] Make sure the user is signed in
- [x] Display all wines in a list
- [x] Add a button to each wine card so that the user can view the wine details.
