### ISSUE TITLE
USER STORY: Register as a New User

### ISSUE THREAD

**Issue by kpsdev1** [kpsdev1/The-Recipe-Blog#2]
As a **User** I can **create an account** so that **I can add my own recipes and comment on other peoples recipes**

# Acceptance Criteria:
Acceptance Criteria 1: A register page where the user can signup
Acceptance Criteria 2: When the user signs up, they should then be logged into their newly created account
Acceptance Criteria 3: Check if the account is already created before creating the new account

# Tasks

- [x] Add HTML from as a registration page on the site, where the user can sign up.
- [x] Verify all data entered into the form
- [x] Verify the account does not already exist
