### ISSUE TITLE
USER STORY: Sign-in / sign-out

### ISSUE THREAD

**Issue by kpsdev1** [kpsdev1/The-Recipe-Blog#7]
As a **User** I can **Sign-in/ Sign-out** so that **can access features when signed in and sign-out so that no one can access my account**

# Acceptance  Criteria 
- Acceptance  Criteria 1: Have a sign-in button on the navbar, that when clicked brings the user to a sign in page.
- Acceptance  Criteria 2: When the user enters their details let them know they are signed in.
- Acceptance  Criteria 3: Have a logout button that the user can click to sign-out.

# Tasks
- [x] HTML form to sign in
- [x] Function to check if the user exist in database, if so let them log in
- [x] Add message to let the user know they are signed in.
